import { getPages } from '@/sanity/sanity-utils';
import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Jay's Awesome Site",
  description: 'Generated by Next.js + Sanity.io',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all page
  const pages = await getPages();

  return (
    <html lang='en'>
      <body className='max-w-3xl min-h-screen mx-3 md:mx-6 lg:mx-auto py-10'>
        <header className='flex items-center justify-between'>
          <Link
            href='/'
            className='bg-gradient-to-r bg-no-repeat from-orange-400 to-purple-600 bg-clip-text text-transparent text-lg font-bold'
          >
            Jay
          </Link>

          <div className='flex items-center gap-5 text-sm text-gray-600'>
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className='hover:underline'
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>

        <main className='py-20'>{children}</main>
      </body>
    </html>
  );
}
