import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Jay's Awesome Site",
  description: 'Generated by Next.js + Sanity.io',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='max-w-3xl min-h-screen mx-3 md:mx-6 lg:mx-auto py-10'>
        <header>
          <Link
            href='/'
            className='bg-gradient-to-r bg-no-repeat from-orange-400 to-purple-600 bg-clip-text text-transparent text-lg font-bold'
          >
            Jay
          </Link>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
